j = "COMBINED MATHEMATICS, BUDDHISM, HINDUISM, CHRISTIANITY, ISLAM, BUDDHIST CIVILIZATION, HINDU CIVILIZATION, ISLAMIC CIVILIZATION, CHRISTIAN CIVILIZATION, BIOLOGY, ECONOMICS, ART, DANCING (INDIGENOUS), DANCING (BHARATHA), ORIENTAL MUSIC, CARNATIC MUSIC, WESTERN MUSIC, LOGIC & SCIENTIFIC METHOD, ENGINEERING TECHNOLOGY, BIO SYSTEMS TECHNOLOGY, BUSINESS STUDIES, AGRICULTURAL SCIENCE, GERMAN, PHYSICS, PALI, SINHALA, TAMIL, CIVIL TECHNOLOGY, MECHANICAL TECHNOLOGY, ELECTRICAL, ELECTRONIC AND INFORMATION TECHNOLOGY, FOOD TECHNOLOGY, AGRO TECHNOLOGY, BIO RESOURCE TECHNOLOGY, BUSINESS STATISTICS, SANSKRIT, CHEMISTRY, SCIENCE FOR TECHNOLOGY, DRAMA & THEATRE (SINAHALA), DRAMA & THEATRE (TAMIL), DRAMA & THEATRE (ENGLISH), POLITICAL SCIENCE, FRENCH, ENGLISH, HOME ECONOMICS, ACCOUNTING, HISTORY OF INDIA, HISTORY OF EUROPE, HISTORY OF MODERN WORLD, ARABIC, MALAY, CHINESE, INFORMATION & COMMUNICATION TECHNOLOGY, HISTORY OF SRI LANKA, HINDI, KOREAN, MATHEMATICS, HIGHER MATHEMATICS, RUSSIAN, GREEK AND ROMAN CIVILIZATION, JAPANESE, GEOGRAPHY, COMMUNICATION & MEDIA STUDIES"

k = j.split(",")
print(len(k))

for i in range(len(k)):
    print(k[i],"   ",i)